// Global Autocomplete Search Bar Extracted Payload
const allCities = [
{name: 'Abbott, TX', url: '/abbott-tx/'},
{name: 'Abernathy, TX', url: '/abernathy-tx/'},
{name: 'Abilene, TX', url: '/abilene-tx/'},
{name: 'Ace, TX', url: '/ace-tx/'},
{name: 'Ackerly, TX', url: '/ackerly-tx/'},
{name: 'Addison, TX', url: '/addison-tx/'},
{name: 'Adkins, TX', url: '/adkins-tx/'},
{name: 'Adrian, TX', url: '/adrian-tx/'},
{name: 'Afton, TX', url: '/afton-tx/'},
{name: 'Agua Dulce, TX', url: '/agua-dulce-tx/'},
{name: 'Aiken, TX', url: '/aiken-tx/'},
{name: 'Alamo, TX', url: '/alamo-tx/'},
{name: 'Alanreed, TX', url: '/alanreed-tx/'},
{name: 'Alba, TX', url: '/alba-tx/'},
{name: 'Albany, TX', url: '/albany-tx/'},
{name: 'Aledo, TX', url: '/aledo-tx/'},
{name: 'Alice, TX', url: '/alice-tx/'},
{name: 'Alief, TX', url: '/alief-tx/'},
{name: 'Allen, TX', url: '/allen-tx/'},
{name: 'Alleyton, TX', url: '/alleyton-tx/'},
{name: 'Allison, TX', url: '/allison-tx/'},
{name: 'Alpine, TX', url: '/alpine-tx/'},
{name: 'Altair, TX', url: '/altair-tx/'},
{name: 'Alto, TX', url: '/alto-tx/'},
{name: 'Alvarado, TX', url: '/alvarado-tx/'},
{name: 'Alvin, TX', url: '/alvin-tx/'},
{name: 'Alvord, TX', url: '/alvord-tx/'},
{name: 'Amarillo, TX', url: '/amarillo-tx/'},
{name: 'Amherst, TX', url: '/amherst-tx/'},
{name: 'Anahuac, TX', url: '/anahuac-tx/'},
{name: 'Anderson, TX', url: '/anderson-tx/'},
{name: 'Andrews, TX', url: '/andrews-tx/'},
{name: 'Angleton, TX', url: '/angleton-tx/'},
{name: 'Anna, TX', url: '/anna-tx/'},
{name: 'Annona, TX', url: '/annona-tx/'},
{name: 'Anson, TX', url: '/anson-tx/'},
{name: 'Anthony, TX', url: '/anthony-tx/'},
{name: 'Anton, TX', url: '/anton-tx/'},
{name: 'Apple Springs, TX', url: '/apple-springs-tx/'},
{name: 'Aquilla, TX', url: '/aquilla-tx/'},
{name: 'Aransas Pass, TX', url: '/aransas-pass-tx/'},
{name: 'Archer City, TX', url: '/archer-city-tx/'},
{name: 'Argyle, TX', url: '/argyle-tx/'},
{name: 'Arlington, TX', url: '/arlington-tx/'},
{name: 'Armstrong, TX', url: '/armstrong-tx/'},
{name: 'Arp, TX', url: '/arp-tx/'},
{name: 'Art, TX', url: '/art-tx/'},
{name: 'Artesia Wells, TX', url: '/artesia-wells-tx/'},
{name: 'Arthur City, TX', url: '/arthur-city-tx/'},
{name: 'Asherton, TX', url: '/asherton-tx/'},
{name: 'Aspermont, TX', url: '/aspermont-tx/'},
{name: 'Atascosa, TX', url: '/atascosa-tx/'},
{name: 'Athens, TX', url: '/athens-tx/'},
{name: 'Atlanta, TX', url: '/atlanta-tx/'},
{name: 'Aubrey, TX', url: '/aubrey-tx/'},
{name: 'Austin, TX', url: '/austin-tx/'},
{name: 'Austwell, TX', url: '/austwell-tx/'},
{name: 'Avalon, TX', url: '/avalon-tx/'},
{name: 'Avery, TX', url: '/avery-tx/'},
{name: 'Avinger, TX', url: '/avinger-tx/'},
{name: 'Avoca, TX', url: '/avoca-tx/'},
{name: 'Axtell, TX', url: '/axtell-tx/'},
{name: 'Azle, TX', url: '/azle-tx/'},
{name: 'Bacliff, TX', url: '/bacliff-tx/'},
{name: 'Bagwell, TX', url: '/bagwell-tx/'},
{name: 'Bailey, TX', url: '/bailey-tx/'},
{name: 'Baird, TX', url: '/baird-tx/'},
{name: 'Ballinger, TX', url: '/ballinger-tx/'},
{name: 'Balmorhea, TX', url: '/balmorhea-tx/'},
{name: 'Bandera, TX', url: '/bandera-tx/'},
{name: 'Bangs, TX', url: '/bangs-tx/'},
{name: 'Banquete, TX', url: '/banquete-tx/'},
{name: 'Bardwell, TX', url: '/bardwell-tx/'},
{name: 'Barker, TX', url: '/barker-tx/'},
{name: 'Barksdale, TX', url: '/barksdale-tx/'},
{name: 'Barnhart, TX', url: '/barnhart-tx/'},
{name: 'Barry, TX', url: '/barry-tx/'},
{name: 'Barstow, TX', url: '/barstow-tx/'},
{name: 'Bartlett, TX', url: '/bartlett-tx/'},
{name: 'Bastrop, TX', url: '/bastrop-tx/'},
{name: 'Batesville, TX', url: '/batesville-tx/'},
{name: 'Batson, TX', url: '/batson-tx/'},
{name: 'Bay City, TX', url: '/bay-city-tx/'},
{name: 'Bayside, TX', url: '/bayside-tx/'},
{name: 'Baytown, TX', url: '/baytown-tx/'},
{name: 'Beasley, TX', url: '/beasley-tx/'},
{name: 'Beaumont, TX', url: '/beaumont-tx/'},
{name: 'Beckville, TX', url: '/beckville-tx/'},
{name: 'Bedford, TX', url: '/bedford-tx/'},
{name: 'Bedias, TX', url: '/bedias-tx/'},
{name: 'Beeville, TX', url: '/beeville-tx/'},
{name: 'Bellaire, TX', url: '/bellaire-tx/'},
{name: 'Bellevue, TX', url: '/bellevue-tx/'},
{name: 'Bells, TX', url: '/bells-tx/'},
{name: 'Bellville, TX', url: '/bellville-tx/'},
{name: 'Belmont, TX', url: '/belmont-tx/'},
{name: 'Belton, TX', url: '/belton-tx/'},
{name: 'Ben Bolt, TX', url: '/ben-bolt-tx/'},
{name: 'Ben Franklin, TX', url: '/ben-franklin-tx/'},
{name: 'Ben Wheeler, TX', url: '/ben-wheeler-tx/'},
{name: 'Benavides, TX', url: '/benavides-tx/'},
{name: 'Bend, TX', url: '/bend-tx/'},
{name: 'Benjamin, TX', url: '/benjamin-tx/'},
{name: 'Berclair, TX', url: '/berclair-tx/'},
{name: 'Bergheim, TX', url: '/bergheim-tx/'},
{name: 'Bertram, TX', url: '/bertram-tx/'},
{name: 'Big Bend National Park, TX', url: '/big-bend-national-park-tx/'},
{name: 'Big Lake, TX', url: '/big-lake-tx/'},
{name: 'Big Sandy, TX', url: '/big-sandy-tx/'},
{name: 'Big Spring, TX', url: '/big-spring-tx/'},
{name: 'Big Wells, TX', url: '/big-wells-tx/'},
{name: 'Bigfoot, TX', url: '/bigfoot-tx/'},
{name: 'Bishop, TX', url: '/bishop-tx/'},
{name: 'Bivins, TX', url: '/bivins-tx/'},
{name: 'Blackwell, TX', url: '/blackwell-tx/'},
{name: 'Blanco, TX', url: '/blanco-tx/'},
{name: 'Blanket, TX', url: '/blanket-tx/'},
{name: 'Bledsoe, TX', url: '/bledsoe-tx/'},
{name: 'Bleiblerville, TX', url: '/bleiblerville-tx/'},
{name: 'Blessing, TX', url: '/blessing-tx/'},
{name: 'Bloomburg, TX', url: '/bloomburg-tx/'},
{name: 'Blooming Grove, TX', url: '/blooming-grove-tx/'},
{name: 'Bloomington, TX', url: '/bloomington-tx/'},
{name: 'Blossom, TX', url: '/blossom-tx/'},
{name: 'Blue Ridge, TX', url: '/blue-ridge-tx/'},
{name: 'Bluegrove, TX', url: '/bluegrove-tx/'},
{name: 'Bluff Dale, TX', url: '/bluff-dale-tx/'},
{name: 'Bluffton, TX', url: '/bluffton-tx/'},
{name: 'Blum, TX', url: '/blum-tx/'},
{name: 'Boerne, TX', url: '/boerne-tx/'},
{name: 'Bogata, TX', url: '/bogata-tx/'},
{name: 'Boling, TX', url: '/boling-tx/'},
{name: 'Bon Wier, TX', url: '/bon-wier-tx/'},
{name: 'Bonham, TX', url: '/bonham-tx/'},
{name: 'Booker, TX', url: '/booker-tx/'},
{name: 'Borger, TX', url: '/borger-tx/'},
{name: 'Bovina, TX', url: '/bovina-tx/'},
{name: 'Bowie, TX', url: '/bowie-tx/'},
{name: 'Boyd, TX', url: '/boyd-tx/'},
{name: 'Boys Ranch, TX', url: '/boys-ranch-tx/'},
{name: 'Brackettville, TX', url: '/brackettville-tx/'},
{name: 'Brady, TX', url: '/brady-tx/'},
{name: 'Brandon, TX', url: '/brandon-tx/'},
{name: 'Brashear, TX', url: '/brashear-tx/'},
{name: 'Brazoria, TX', url: '/brazoria-tx/'},
{name: 'Breckenridge, TX', url: '/breckenridge-tx/'},
{name: 'Bremond, TX', url: '/bremond-tx/'},
{name: 'Brenham, TX', url: '/brenham-tx/'},
{name: 'Bridge City, TX', url: '/bridge-city-tx/'},
{name: 'Bridgeport, TX', url: '/bridgeport-tx/'},
{name: 'Briggs, TX', url: '/briggs-tx/'},
{name: 'Briscoe, TX', url: '/briscoe-tx/'},
{name: 'Broaddus, TX', url: '/broaddus-tx/'},
{name: 'Bronson, TX', url: '/bronson-tx/'},
{name: 'Bronte, TX', url: '/bronte-tx/'},
{name: 'Brookeland, TX', url: '/brookeland-tx/'},
{name: 'Brookesmith, TX', url: '/brookesmith-tx/'},
{name: 'Brookshire, TX', url: '/brookshire-tx/'},
{name: 'Brookston, TX', url: '/brookston-tx/'},
{name: 'Brownfield, TX', url: '/brownfield-tx/'},
{name: 'Brownsboro, TX', url: '/brownsboro-tx/'},
{name: 'Brownsville, TX', url: '/brownsville-tx/'},
{name: 'Brownwood, TX', url: '/brownwood-tx/'},
{name: 'Bruceville, TX', url: '/bruceville-tx/'},
{name: 'Bruni, TX', url: '/bruni-tx/'},
{name: 'Bryan, TX', url: '/bryan-tx/'},
{name: 'Bryson, TX', url: '/bryson-tx/'},
{name: 'Buchanan Dam, TX', url: '/buchanan-dam-tx/'},
{name: 'Buckholts, TX', url: '/buckholts-tx/'},
{name: 'Buda, TX', url: '/buda-tx/'},
{name: 'Buffalo Gap, TX', url: '/buffalo-gap-tx/'},
{name: 'Buffalo, TX', url: '/buffalo-tx/'},
{name: 'Bula, TX', url: '/bula-tx/'},
{name: 'Bullard, TX', url: '/bullard-tx/'},
{name: 'Bulverde, TX', url: '/bulverde-tx/'},
{name: 'Buna, TX', url: '/buna-tx/'},
{name: 'Burkburnett, TX', url: '/burkburnett-tx/'},
{name: 'Burkett, TX', url: '/burkett-tx/'},
{name: 'Burkeville, TX', url: '/burkeville-tx/'},
{name: 'Burleson, TX', url: '/burleson-tx/'},
{name: 'Burlington, TX', url: '/burlington-tx/'},
{name: 'Burnet, TX', url: '/burnet-tx/'},
{name: 'Burton, TX', url: '/burton-tx/'},
{name: 'Bushland, TX', url: '/bushland-tx/'},
{name: 'Byers, TX', url: '/byers-tx/'},
{name: 'Bynum, TX', url: '/bynum-tx/'},
{name: 'Cactus, TX', url: '/cactus-tx/'},
{name: 'Caddo Mills, TX', url: '/caddo-mills-tx/'},
{name: 'Caddo, TX', url: '/caddo-tx/'},
{name: 'Caldwell, TX', url: '/caldwell-tx/'},
{name: 'Call, TX', url: '/call-tx/'},
{name: 'Calliham, TX', url: '/calliham-tx/'},
{name: 'Calvert, TX', url: '/calvert-tx/'},
{name: 'Camden, TX', url: '/camden-tx/'},
{name: 'Cameron, TX', url: '/cameron-tx/'},
{name: 'Camp Wood, TX', url: '/camp-wood-tx/'},
{name: 'Campbell, TX', url: '/campbell-tx/'},
{name: 'Campbellton, TX', url: '/campbellton-tx/'},
{name: 'Canadian, TX', url: '/canadian-tx/'},
{name: 'Canton, TX', url: '/canton-tx/'},
{name: 'Canutillo, TX', url: '/canutillo-tx/'},
{name: 'Canyon Lake, TX', url: '/canyon-lake-tx/'},
{name: 'Canyon, TX', url: '/canyon-tx/'},
{name: 'Carbon, TX', url: '/carbon-tx/'},
{name: 'Carlsbad, TX', url: '/carlsbad-tx/'},
{name: 'Carlton, TX', url: '/carlton-tx/'},
{name: 'Carmine, TX', url: '/carmine-tx/'},
{name: 'Carrizo Springs, TX', url: '/carrizo-springs-tx/'},
{name: 'Carrollton, TX', url: '/carrollton-tx/'},
{name: 'Carthage, TX', url: '/carthage-tx/'},
{name: 'Cason, TX', url: '/cason-tx/'},
{name: 'Castell, TX', url: '/castell-tx/'},
{name: 'Castroville, TX', url: '/castroville-tx/'},
{name: 'Cat Spring, TX', url: '/cat-spring-tx/'},
{name: 'Catarina, TX', url: '/catarina-tx/'},
{name: 'Cayuga, TX', url: '/cayuga-tx/'},
{name: 'Cedar Creek, TX', url: '/cedar-creek-tx/'},
{name: 'Cedar Hill, TX', url: '/cedar-hill-tx/'},
{name: 'Cedar Lane, TX', url: '/cedar-lane-tx/'},
{name: 'Cedar Park, TX', url: '/cedar-park-tx/'},
{name: 'Cee Vee, TX', url: '/cee-vee-tx/'},
{name: 'Celeste, TX', url: '/celeste-tx/'},
{name: 'Celina, TX', url: '/celina-tx/'},
{name: 'Center Point, TX', url: '/center-point-tx/'},
{name: 'Center, TX', url: '/center-tx/'},
{name: 'Centerville, TX', url: '/centerville-tx/'},
{name: 'Centralia, TX', url: '/centralia-tx/'},
{name: 'Chandler, TX', url: '/chandler-tx/'},
{name: 'Channelview, TX', url: '/channelview-tx/'},
{name: 'Channing, TX', url: '/channing-tx/'},
{name: 'Chapman Ranch, TX', url: '/chapman-ranch-tx/'},
{name: 'Chappell Hill, TX', url: '/chappell-hill-tx/'},
{name: 'Charlotte, TX', url: '/charlotte-tx/'},
{name: 'Chatfield, TX', url: '/chatfield-tx/'},
{name: 'Cherokee, TX', url: '/cherokee-tx/'},
{name: 'Chester, TX', url: '/chester-tx/'},
{name: 'Chico, TX', url: '/chico-tx/'},
{name: 'Chicota, TX', url: '/chicota-tx/'},
{name: 'Childress, TX', url: '/childress-tx/'},
{name: 'Chillicothe, TX', url: '/chillicothe-tx/'},
{name: 'Chilton, TX', url: '/chilton-tx/'},
{name: 'China Spring, TX', url: '/china-spring-tx/'},
{name: 'China, TX', url: '/china-tx/'},
{name: 'Chireno, TX', url: '/chireno-tx/'},
{name: 'Chriesman, TX', url: '/chriesman-tx/'},
{name: 'Christine, TX', url: '/christine-tx/'},
{name: 'Christoval, TX', url: '/christoval-tx/'},
{name: 'Cibolo, TX', url: '/cibolo-tx/'},
{name: 'Cisco, TX', url: '/cisco-tx/'},
{name: 'Clarendon, TX', url: '/clarendon-tx/'},
{name: 'Clarksville, TX', url: '/clarksville-tx/'},
{name: 'Claude, TX', url: '/claude-tx/'},
{name: 'Clayton, TX', url: '/clayton-tx/'},
{name: 'Cleburne, TX', url: '/cleburne-tx/'},
{name: 'Cleveland, TX', url: '/cleveland-tx/'},
{name: 'Clifton, TX', url: '/clifton-tx/'},
{name: 'Clint, TX', url: '/clint-tx/'},
{name: 'Clute, TX', url: '/clute-tx/'},
{name: 'Clyde, TX', url: '/clyde-tx/'},
{name: 'Coahoma, TX', url: '/coahoma-tx/'},
{name: 'Coldspring, TX', url: '/coldspring-tx/'},
{name: 'Coleman, TX', url: '/coleman-tx/'},
{name: 'College Station, TX', url: '/college-station-tx/'},
{name: 'Collegeport, TX', url: '/collegeport-tx/'},
{name: 'Colleyville, TX', url: '/colleyville-tx/'},
{name: 'Collinsville, TX', url: '/collinsville-tx/'},
{name: 'Colmesneil, TX', url: '/colmesneil-tx/'},
{name: 'Colorado City, TX', url: '/colorado-city-tx/'},
{name: 'Columbus, TX', url: '/columbus-tx/'},
{name: 'Comanche, TX', url: '/comanche-tx/'},
{name: 'Combes, TX', url: '/combes-tx/'},
{name: 'Comfort, TX', url: '/comfort-tx/'},
{name: 'Commerce, TX', url: '/commerce-tx/'},
{name: 'Como, TX', url: '/como-tx/'},
{name: 'Comstock, TX', url: '/comstock-tx/'},
{name: 'Concan, TX', url: '/concan-tx/'},
{name: 'Concepcion, TX', url: '/concepcion-tx/'},
{name: 'Concord, TX', url: '/concord-tx/'},
{name: 'Conroe, TX', url: '/conroe-tx/'},
{name: 'Converse, TX', url: '/converse-tx/'},
{name: 'Cookville, TX', url: '/cookville-tx/'},
{name: 'Coolidge, TX', url: '/coolidge-tx/'},
{name: 'Cooper, TX', url: '/cooper-tx/'},
{name: 'Copeville, TX', url: '/copeville-tx/'},
{name: 'Coppell, TX', url: '/coppell-tx/'},
{name: 'Copperas Cove, TX', url: '/copperas-cove-tx/'},
{name: 'Corpus Christi, TX', url: '/corpus-christi-tx/'},
{name: 'Corrigan, TX', url: '/corrigan-tx/'},
{name: 'Corsicana, TX', url: '/corsicana-tx/'},
{name: 'Cost, TX', url: '/cost-tx/'},
{name: 'Cotton Center, TX', url: '/cotton-center-tx/'},
{name: 'Cotulla, TX', url: '/cotulla-tx/'},
{name: 'Coupland, TX', url: '/coupland-tx/'},
{name: 'Covington, TX', url: '/covington-tx/'},
{name: 'Coyanosa, TX', url: '/coyanosa-tx/'},
{name: 'Crandall, TX', url: '/crandall-tx/'},
{name: 'Crane, TX', url: '/crane-tx/'},
{name: 'Cranfills Gap, TX', url: '/cranfills-gap-tx/'},
{name: 'Crawford, TX', url: '/crawford-tx/'},
{name: 'Cresson, TX', url: '/cresson-tx/'},
{name: 'Crockett, TX', url: '/crockett-tx/'},
{name: 'Crosby, TX', url: '/crosby-tx/'},
{name: 'Crosbyton, TX', url: '/crosbyton-tx/'},
{name: 'Cross Plains, TX', url: '/cross-plains-tx/'},
{name: 'Crowell, TX', url: '/crowell-tx/'},
{name: 'Crowley, TX', url: '/crowley-tx/'},
{name: 'Crp Christi, TX', url: '/crp-christi-tx/'},
{name: 'Crystal City, TX', url: '/crystal-city-tx/'},
{name: 'Cuero, TX', url: '/cuero-tx/'},
{name: 'Cumby, TX', url: '/cumby-tx/'},
{name: 'Cuney, TX', url: '/cuney-tx/'},
{name: 'Cunningham, TX', url: '/cunningham-tx/'},
{name: 'Cushing, TX', url: '/cushing-tx/'},
{name: 'Cypress, TX', url: '/cypress-tx/'},
{name: 'D Hanis, TX', url: '/d-hanis-tx/'},
{name: 'Daingerfield, TX', url: '/daingerfield-tx/'},
{name: 'Daisetta, TX', url: '/daisetta-tx/'},
{name: 'Dale, TX', url: '/dale-tx/'},
{name: 'Dalhart, TX', url: '/dalhart-tx/'},
{name: 'Dallardsville, TX', url: '/dallardsville-tx/'},
{name: 'Dallas, TX', url: '/dallas-tx/'},
{name: 'Damon, TX', url: '/damon-tx/'},
{name: 'Danbury, TX', url: '/danbury-tx/'},
{name: 'Danciger, TX', url: '/danciger-tx/'},
{name: 'Danevang, TX', url: '/danevang-tx/'},
{name: 'Darrouzett, TX', url: '/darrouzett-tx/'},
{name: 'Davilla, TX', url: '/davilla-tx/'},
{name: 'Dawn, TX', url: '/dawn-tx/'},
{name: 'Dawson, TX', url: '/dawson-tx/'},
{name: 'Dayton, TX', url: '/dayton-tx/'},
{name: 'De Berry, TX', url: '/de-berry-tx/'},
{name: 'De Kalb, TX', url: '/de-kalb-tx/'},
{name: 'De Leon, TX', url: '/de-leon-tx/'},
{name: 'Deanville, TX', url: '/deanville-tx/'},
{name: 'Decatur, TX', url: '/decatur-tx/'},
{name: 'Deer Park, TX', url: '/deer-park-tx/'},
{name: 'Del Rio, TX', url: '/del-rio-tx/'},
{name: 'Del Valle, TX', url: '/del-valle-tx/'},
{name: 'Dell City, TX', url: '/dell-city-tx/'},
{name: 'Delmita, TX', url: '/delmita-tx/'},
{name: 'Denison, TX', url: '/denison-tx/'},
{name: 'Dennis, TX', url: '/dennis-tx/'},
{name: 'Denton, TX', url: '/denton-tx/'},
{name: 'Denver City, TX', url: '/denver-city-tx/'},
{name: 'Deport, TX', url: '/deport-tx/'},
{name: 'Desdemona, TX', url: '/desdemona-tx/'},
{name: 'Desoto, TX', url: '/desoto-tx/'},
{name: 'Detroit, TX', url: '/detroit-tx/'},
{name: 'Devers, TX', url: '/devers-tx/'},
{name: 'Devine, TX', url: '/devine-tx/'},
{name: 'Deweyville, TX', url: '/deweyville-tx/'},
{name: 'Diana, TX', url: '/diana-tx/'},
{name: 'Diboll, TX', url: '/diboll-tx/'},
{name: 'Dickens, TX', url: '/dickens-tx/'},
{name: 'Dickinson, TX', url: '/dickinson-tx/'},
{name: 'Dike, TX', url: '/dike-tx/'},
{name: 'Dilley, TX', url: '/dilley-tx/'},
{name: 'Dime Box, TX', url: '/dime-box-tx/'},
{name: 'Dimmitt, TX', url: '/dimmitt-tx/'},
{name: 'Dinero, TX', url: '/dinero-tx/'},
{name: 'Dobbin, TX', url: '/dobbin-tx/'},
{name: 'Dodd City, TX', url: '/dodd-city-tx/'},
{name: 'Dodge, TX', url: '/dodge-tx/'},
{name: 'Dodson, TX', url: '/dodson-tx/'},
{name: 'Donie, TX', url: '/donie-tx/'},
{name: 'Donna, TX', url: '/donna-tx/'},
{name: 'Doole, TX', url: '/doole-tx/'},
{name: 'Doss, TX', url: '/doss-tx/'},
{name: 'Doucette, TX', url: '/doucette-tx/'},
{name: 'Dougherty, TX', url: '/dougherty-tx/'},
{name: 'Douglass, TX', url: '/douglass-tx/'},
{name: 'Douglassville, TX', url: '/douglassville-tx/'},
{name: 'Driftwood, TX', url: '/driftwood-tx/'},
{name: 'Dripping Springs, TX', url: '/dripping-springs-tx/'},
{name: 'Driscoll, TX', url: '/driscoll-tx/'},
{name: 'Dryden, TX', url: '/dryden-tx/'},
{name: 'Dublin, TX', url: '/dublin-tx/'},
{name: 'Dumas, TX', url: '/dumas-tx/'},
{name: 'Duncanville, TX', url: '/duncanville-tx/'},
{name: 'Dunn, TX', url: '/dunn-tx/'},
{name: 'Dyess Afb, TX', url: '/dyess-afb-tx/'},
{name: 'Eagle Lake, TX', url: '/eagle-lake-tx/'},
{name: 'Eagle Pass, TX', url: '/eagle-pass-tx/'},
{name: 'Early, TX', url: '/early-tx/'},
{name: 'Earth, TX', url: '/earth-tx/'},
{name: 'East Bernard, TX', url: '/east-bernard-tx/'},
{name: 'Eastland, TX', url: '/eastland-tx/'},
{name: 'Easton, TX', url: '/easton-tx/'},
{name: 'Ecleto, TX', url: '/ecleto-tx/'},
{name: 'Ector, TX', url: '/ector-tx/'},
{name: 'Edcouch, TX', url: '/edcouch-tx/'},
{name: 'Eddy, TX', url: '/eddy-tx/'},
{name: 'Eden, TX', url: '/eden-tx/'},
{name: 'Edgewood, TX', url: '/edgewood-tx/'},
{name: 'Edinburg, TX', url: '/edinburg-tx/'},
{name: 'Edmonson, TX', url: '/edmonson-tx/'},
{name: 'Edna, TX', url: '/edna-tx/'},
{name: 'Edroy, TX', url: '/edroy-tx/'},
{name: 'Egypt, TX', url: '/egypt-tx/'},
{name: 'El Campo, TX', url: '/el-campo-tx/'},
{name: 'El Indio, TX', url: '/el-indio-tx/'},
{name: 'El Paso, TX', url: '/el-paso-tx/'},
{name: 'Eldorado, TX', url: '/eldorado-tx/'},
{name: 'Electra, TX', url: '/electra-tx/'},
{name: 'Elgin, TX', url: '/elgin-tx/'},
{name: 'Elkhart, TX', url: '/elkhart-tx/'},
{name: 'Ellinger, TX', url: '/ellinger-tx/'},
{name: 'Elm Mott, TX', url: '/elm-mott-tx/'},
{name: 'Elmaton, TX', url: '/elmaton-tx/'},
{name: 'Elmendorf, TX', url: '/elmendorf-tx/'},
{name: 'Elmo, TX', url: '/elmo-tx/'},
{name: 'Elsa, TX', url: '/elsa-tx/'},
{name: 'Elysian Fields, TX', url: '/elysian-fields-tx/'},
{name: 'Emory, TX', url: '/emory-tx/'},
{name: 'Encinal, TX', url: '/encinal-tx/'},
{name: 'Encino, TX', url: '/encino-tx/'},
{name: 'Energy, TX', url: '/energy-tx/'},
{name: 'Enloe, TX', url: '/enloe-tx/'},
{name: 'Ennis, TX', url: '/ennis-tx/'},
{name: 'Enochs, TX', url: '/enochs-tx/'},
{name: 'Eola, TX', url: '/eola-tx/'},
{name: 'Era, TX', url: '/era-tx/'},
{name: 'Estelline, TX', url: '/estelline-tx/'},
{name: 'Etoile, TX', url: '/etoile-tx/'},
{name: 'Euless, TX', url: '/euless-tx/'},
{name: 'Eustace, TX', url: '/eustace-tx/'},
{name: 'Evadale, TX', url: '/evadale-tx/'},
{name: 'Evant, TX', url: '/evant-tx/'},
{name: 'Fabens, TX', url: '/fabens-tx/'},
{name: 'Fairfield, TX', url: '/fairfield-tx/'},
{name: 'Falcon Heights, TX', url: '/falcon-heights-tx/'},
{name: 'Falfurrias, TX', url: '/falfurrias-tx/'},
{name: 'Falls City, TX', url: '/falls-city-tx/'},
{name: 'Fannin, TX', url: '/fannin-tx/'},
{name: 'Farmersville, TX', url: '/farmersville-tx/'},
{name: 'Farnsworth, TX', url: '/farnsworth-tx/'},
{name: 'Farwell, TX', url: '/farwell-tx/'},
{name: 'Fate, TX', url: '/fate-tx/'},
{name: 'Fayetteville, TX', url: '/fayetteville-tx/'},
{name: 'Fentress, TX', url: '/fentress-tx/'},
{name: 'Ferris, TX', url: '/ferris-tx/'},
{name: 'Fieldton, TX', url: '/fieldton-tx/'},
{name: 'Fischer, TX', url: '/fischer-tx/'},
{name: 'Flat, TX', url: '/flat-tx/'},
{name: 'Flatonia, TX', url: '/flatonia-tx/'},
{name: 'Flint, TX', url: '/flint-tx/'},
{name: 'Flomot, TX', url: '/flomot-tx/'},
{name: 'Florence, TX', url: '/florence-tx/'},
{name: 'Floresville, TX', url: '/floresville-tx/'},
{name: 'Flower Mound, TX', url: '/flower-mound-tx/'},
{name: 'Floydada, TX', url: '/floydada-tx/'},
{name: 'Fluvanna, TX', url: '/fluvanna-tx/'},
{name: 'Flynn, TX', url: '/flynn-tx/'},
{name: 'Follett, TX', url: '/follett-tx/'},
{name: 'Forestburg, TX', url: '/forestburg-tx/'},
{name: 'Forney, TX', url: '/forney-tx/'},
{name: 'Forreston, TX', url: '/forreston-tx/'},
{name: 'Forsan, TX', url: '/forsan-tx/'},
{name: 'Fort Bliss, TX', url: '/fort-bliss-tx/'},
{name: 'Fort Davis, TX', url: '/fort-davis-tx/'},
{name: 'Fort Hancock, TX', url: '/fort-hancock-tx/'},
{name: 'Fort Mc Kavett, TX', url: '/fort-mc-kavett-tx/'},
{name: 'Fort Stockton, TX', url: '/fort-stockton-tx/'},
{name: 'Fort Worth, TX', url: '/fort-worth-tx/'},
{name: 'Fowlerton, TX', url: '/fowlerton-tx/'},
{name: 'Francitas, TX', url: '/francitas-tx/'},
{name: 'Franklin, TX', url: '/franklin-tx/'},
{name: 'Frankston, TX', url: '/frankston-tx/'},
{name: 'Fred, TX', url: '/fred-tx/'},
{name: 'Fredericksburg, TX', url: '/fredericksburg-tx/'},
{name: 'Fredonia, TX', url: '/fredonia-tx/'},
{name: 'Freeport, TX', url: '/freeport-tx/'},
{name: 'Freer, TX', url: '/freer-tx/'},
{name: 'Fresno, TX', url: '/fresno-tx/'},
{name: 'Friendswood, TX', url: '/friendswood-tx/'},
{name: 'Friona, TX', url: '/friona-tx/'},
{name: 'Frisco, TX', url: '/frisco-tx/'},
{name: 'Fritch, TX', url: '/fritch-tx/'},
{name: 'Frost, TX', url: '/frost-tx/'},
{name: 'Fruitvale, TX', url: '/fruitvale-tx/'},
{name: 'Fulshear, TX', url: '/fulshear-tx/'},
{name: 'Fulton, TX', url: '/fulton-tx/'},
{name: 'Gail, TX', url: '/gail-tx/'},
{name: 'Gainesville, TX', url: '/gainesville-tx/'},
{name: 'Galena Park, TX', url: '/galena-park-tx/'},
{name: 'Gallatin, TX', url: '/gallatin-tx/'},
{name: 'Galveston, TX', url: '/galveston-tx/'},
{name: 'Ganado, TX', url: '/ganado-tx/'},
{name: 'Garciasville, TX', url: '/garciasville-tx/'},
{name: 'Garden City, TX', url: '/garden-city-tx/'},
{name: 'Gardendale, TX', url: '/gardendale-tx/'},
{name: 'Garland, TX', url: '/garland-tx/'},
{name: 'Garrison, TX', url: '/garrison-tx/'},
{name: 'Garwood, TX', url: '/garwood-tx/'},
{name: 'Gary, TX', url: '/gary-tx/'},
{name: 'Gatesville, TX', url: '/gatesville-tx/'},
{name: 'Gause, TX', url: '/gause-tx/'},
{name: 'George West, TX', url: '/george-west-tx/'},
{name: 'Georgetown, TX', url: '/georgetown-tx/'},
{name: 'Geronimo, TX', url: '/geronimo-tx/'},
{name: 'Giddings, TX', url: '/giddings-tx/'},
{name: 'Gilchrist, TX', url: '/gilchrist-tx/'},
{name: 'Gillett, TX', url: '/gillett-tx/'},
{name: 'Gilmer, TX', url: '/gilmer-tx/'},
{name: 'Girard, TX', url: '/girard-tx/'},
{name: 'Girvin, TX', url: '/girvin-tx/'},
{name: 'Gladewater, TX', url: '/gladewater-tx/'},
{name: 'Glen Flora, TX', url: '/glen-flora-tx/'},
{name: 'Glen Rose, TX', url: '/glen-rose-tx/'},
{name: 'Glidden, TX', url: '/glidden-tx/'},
{name: 'Gober, TX', url: '/gober-tx/'},
{name: 'Godley, TX', url: '/godley-tx/'},
{name: 'Golden, TX', url: '/golden-tx/'},
{name: 'Goldsboro, TX', url: '/goldsboro-tx/'},
{name: 'Goldsmith, TX', url: '/goldsmith-tx/'},
{name: 'Goldthwaite, TX', url: '/goldthwaite-tx/'},
{name: 'Goliad, TX', url: '/goliad-tx/'},
{name: 'Gonzales, TX', url: '/gonzales-tx/'},
{name: 'Goodfellow Afb, TX', url: '/goodfellow-afb-tx/'},
{name: 'Goodrich, TX', url: '/goodrich-tx/'},
{name: 'Gordon, TX', url: '/gordon-tx/'},
{name: 'Gordonville, TX', url: '/gordonville-tx/'},
{name: 'Goree, TX', url: '/goree-tx/'},
{name: 'Gorman, TX', url: '/gorman-tx/'},
{name: 'Gouldbusk, TX', url: '/gouldbusk-tx/'},
{name: 'Graford, TX', url: '/graford-tx/'},
{name: 'Graham, TX', url: '/graham-tx/'},
{name: 'Granbury, TX', url: '/granbury-tx/'},
{name: 'Grand Prairie, TX', url: '/grand-prairie-tx/'},
{name: 'Grand Saline, TX', url: '/grand-saline-tx/'},
{name: 'Grandfalls, TX', url: '/grandfalls-tx/'},
{name: 'Grandview, TX', url: '/grandview-tx/'},
{name: 'Granger, TX', url: '/granger-tx/'},
{name: 'Grapeland, TX', url: '/grapeland-tx/'},
{name: 'Grapevine, TX', url: '/grapevine-tx/'},
{name: 'Greenville, TX', url: '/greenville-tx/'},
{name: 'Greenwood, TX', url: '/greenwood-tx/'},
{name: 'Gregory, TX', url: '/gregory-tx/'},
{name: 'Groesbeck, TX', url: '/groesbeck-tx/'},
{name: 'Groom, TX', url: '/groom-tx/'},
{name: 'Groves, TX', url: '/groves-tx/'},
{name: 'Groveton, TX', url: '/groveton-tx/'},
{name: 'Grulla, TX', url: '/grulla-tx/'},
{name: 'Gruver, TX', url: '/gruver-tx/'},
{name: 'Guerra, TX', url: '/guerra-tx/'},
{name: 'Gunter, TX', url: '/gunter-tx/'},
{name: 'Gustine, TX', url: '/gustine-tx/'},
{name: 'Guthrie, TX', url: '/guthrie-tx/'},
{name: 'Guy, TX', url: '/guy-tx/'},
{name: 'Hale Center, TX', url: '/hale-center-tx/'},
{name: 'Hallettsville, TX', url: '/hallettsville-tx/'},
{name: 'Hallsville, TX', url: '/hallsville-tx/'},
{name: 'Haltom City, TX', url: '/haltom-city-tx/'},
{name: 'Hamilton, TX', url: '/hamilton-tx/'},
{name: 'Hamlin, TX', url: '/hamlin-tx/'},
{name: 'Hamshire, TX', url: '/hamshire-tx/'},
{name: 'Hankamer, TX', url: '/hankamer-tx/'},
{name: 'Happy, TX', url: '/happy-tx/'},
{name: 'Hardin, TX', url: '/hardin-tx/'},
{name: 'Hargill, TX', url: '/hargill-tx/'},
{name: 'Harker Heights, TX', url: '/harker-heights-tx/'},
{name: 'Harleton, TX', url: '/harleton-tx/'},
{name: 'Harlingen, TX', url: '/harlingen-tx/'},
{name: 'Harper, TX', url: '/harper-tx/'},
{name: 'Harrold, TX', url: '/harrold-tx/'},
{name: 'Hart, TX', url: '/hart-tx/'},
{name: 'Hartley, TX', url: '/hartley-tx/'},
{name: 'Harwood, TX', url: '/harwood-tx/'},
{name: 'Haskell, TX', url: '/haskell-tx/'},
{name: 'Haslet, TX', url: '/haslet-tx/'},
{name: 'Hawkins, TX', url: '/hawkins-tx/'},
{name: 'Hawley, TX', url: '/hawley-tx/'},
{name: 'Hearne, TX', url: '/hearne-tx/'},
{name: 'Hebbronville, TX', url: '/hebbronville-tx/'},
{name: 'Hedley, TX', url: '/hedley-tx/'},
{name: 'Heidenheimer, TX', url: '/heidenheimer-tx/'},
{name: 'Helotes, TX', url: '/helotes-tx/'},
{name: 'Hemphill, TX', url: '/hemphill-tx/'},
{name: 'Hempstead, TX', url: '/hempstead-tx/'},
{name: 'Henderson, TX', url: '/henderson-tx/'},
{name: 'Henrietta, TX', url: '/henrietta-tx/'},
{name: 'Hereford, TX', url: '/hereford-tx/'},
{name: 'Hermleigh, TX', url: '/hermleigh-tx/'},
{name: 'Hewitt, TX', url: '/hewitt-tx/'},
{name: 'Hext, TX', url: '/hext-tx/'},
{name: 'Hico, TX', url: '/hico-tx/'},
{name: 'Hidalgo, TX', url: '/hidalgo-tx/'},
{name: 'Higgins, TX', url: '/higgins-tx/'},
{name: 'High Island, TX', url: '/high-island-tx/'},
{name: 'Highlands, TX', url: '/highlands-tx/'},
{name: 'Hillister, TX', url: '/hillister-tx/'},
{name: 'Hillsboro, TX', url: '/hillsboro-tx/'},
{name: 'Hitchcock, TX', url: '/hitchcock-tx/'},
{name: 'Hobson, TX', url: '/hobson-tx/'},
{name: 'Hochheim, TX', url: '/hochheim-tx/'},
{name: 'Hockley, TX', url: '/hockley-tx/'},
{name: 'Holland, TX', url: '/holland-tx/'},
{name: 'Holliday, TX', url: '/holliday-tx/'},
{name: 'Hondo, TX', url: '/hondo-tx/'},
{name: 'Honey Grove, TX', url: '/honey-grove-tx/'},
{name: 'Hooks, TX', url: '/hooks-tx/'},
{name: 'Horseshoe Bay, TX', url: '/horseshoe-bay-tx/'},
{name: 'Houston, TX', url: '/houston-tx/'},
{name: 'Howe, TX', url: '/howe-tx/'},
{name: 'Hubbard, TX', url: '/hubbard-tx/'},
{name: 'Huffman, TX', url: '/huffman-tx/'},
{name: 'Hufsmith, TX', url: '/hufsmith-tx/'},
{name: 'Hughes Springs, TX', url: '/hughes-springs-tx/'},
{name: 'Hull, TX', url: '/hull-tx/'},
{name: 'Humble, TX', url: '/humble-tx/'},
{name: 'Hungerford, TX', url: '/hungerford-tx/'},
{name: 'Hunt, TX', url: '/hunt-tx/'},
{name: 'Huntington, TX', url: '/huntington-tx/'},
{name: 'Huntsville, TX', url: '/huntsville-tx/'},
{name: 'Hurst, TX', url: '/hurst-tx/'},
{name: 'Hutchins, TX', url: '/hutchins-tx/'},
{name: 'Hutto, TX', url: '/hutto-tx/'},
{name: 'Hye, TX', url: '/hye-tx/'},
{name: 'Idalou, TX', url: '/idalou-tx/'},
{name: 'Imperial, TX', url: '/imperial-tx/'},
{name: 'Industry, TX', url: '/industry-tx/'},
{name: 'Inez, TX', url: '/inez-tx/'},
{name: 'Ingleside, TX', url: '/ingleside-tx/'},
{name: 'Ingram, TX', url: '/ingram-tx/'},
{name: 'Iola, TX', url: '/iola-tx/'},
{name: 'Iowa Park, TX', url: '/iowa-park-tx/'},
{name: 'Ira, TX', url: '/ira-tx/'},
{name: 'Iraan, TX', url: '/iraan-tx/'},
{name: 'Iredell, TX', url: '/iredell-tx/'},
{name: 'Irene, TX', url: '/irene-tx/'},
{name: 'Irving, TX', url: '/irving-tx/'},
{name: 'Italy, TX', url: '/italy-tx/'},
{name: 'Itasca, TX', url: '/itasca-tx/'},
{name: 'Ivanhoe, TX', url: '/ivanhoe-tx/'},
{name: 'Jacksboro, TX', url: '/jacksboro-tx/'},
{name: 'Jacksonville, TX', url: '/jacksonville-tx/'},
{name: 'Jarrell, TX', url: '/jarrell-tx/'},
{name: 'Jasper, TX', url: '/jasper-tx/'},
{name: 'Jayton, TX', url: '/jayton-tx/'},
{name: 'Jefferson, TX', url: '/jefferson-tx/'},
{name: 'Jermyn, TX', url: '/jermyn-tx/'},
{name: 'Jewett, TX', url: '/jewett-tx/'},
{name: 'Joaquin, TX', url: '/joaquin-tx/'},
{name: 'Johnson City, TX', url: '/johnson-city-tx/'},
{name: 'Joinerville, TX', url: '/joinerville-tx/'},
{name: 'Jonesboro, TX', url: '/jonesboro-tx/'},
{name: 'Jonesville, TX', url: '/jonesville-tx/'},
{name: 'Josephine, TX', url: '/josephine-tx/'},
{name: 'Joshua, TX', url: '/joshua-tx/'},
{name: 'Jourdanton, TX', url: '/jourdanton-tx/'},
{name: 'Judson, TX', url: '/judson-tx/'},
{name: 'Junction, TX', url: '/junction-tx/'},
{name: 'Justiceburg, TX', url: '/justiceburg-tx/'},
{name: 'Justin, TX', url: '/justin-tx/'},
{name: 'Kamay, TX', url: '/kamay-tx/'},
{name: 'Karnack, TX', url: '/karnack-tx/'},
{name: 'Karnes City, TX', url: '/karnes-city-tx/'},
{name: 'Katy, TX', url: '/katy-tx/'},
{name: 'Kaufman, TX', url: '/kaufman-tx/'},
{name: 'Keene, TX', url: '/keene-tx/'},
{name: 'Keller, TX', url: '/keller-tx/'},
{name: 'Kemah, TX', url: '/kemah-tx/'},
{name: 'Kemp, TX', url: '/kemp-tx/'},
{name: 'Kempner, TX', url: '/kempner-tx/'},
{name: 'Kendalia, TX', url: '/kendalia-tx/'},
{name: 'Kendleton, TX', url: '/kendleton-tx/'},
{name: 'Kenedy, TX', url: '/kenedy-tx/'},
{name: 'Kennard, TX', url: '/kennard-tx/'},
{name: 'Kennedale, TX', url: '/kennedale-tx/'},
{name: 'Kenney, TX', url: '/kenney-tx/'},
{name: 'Kerens, TX', url: '/kerens-tx/'},
{name: 'Kermit, TX', url: '/kermit-tx/'},
{name: 'Kerrick, TX', url: '/kerrick-tx/'},
{name: 'Kerrville, TX', url: '/kerrville-tx/'},
{name: 'Kildare, TX', url: '/kildare-tx/'},
{name: 'Kilgore, TX', url: '/kilgore-tx/'},
{name: 'Killeen, TX', url: '/killeen-tx/'},
{name: 'Kingsbury, TX', url: '/kingsbury-tx/'},
{name: 'Kingsland, TX', url: '/kingsland-tx/'},
{name: 'Kingsville, TX', url: '/kingsville-tx/'},
{name: 'Kingwood, TX', url: '/kingwood-tx/'},
{name: 'Kirbyville, TX', url: '/kirbyville-tx/'},
{name: 'Kirvin, TX', url: '/kirvin-tx/'},
{name: 'Klondike, TX', url: '/klondike-tx/'},
{name: 'Knickerbocker, TX', url: '/knickerbocker-tx/'},
{name: 'Knippa, TX', url: '/knippa-tx/'},
{name: 'Knott, TX', url: '/knott-tx/'},
{name: 'Knox City, TX', url: '/knox-city-tx/'},
{name: 'Kopperl, TX', url: '/kopperl-tx/'},
{name: 'Kosse, TX', url: '/kosse-tx/'},
{name: 'Kountze, TX', url: '/kountze-tx/'},
{name: 'Kress, TX', url: '/kress-tx/'},
{name: 'Krum, TX', url: '/krum-tx/'},
{name: 'Kurten, TX', url: '/kurten-tx/'},
{name: 'Kyle, TX', url: '/kyle-tx/'},
{name: 'La Blanca, TX', url: '/la-blanca-tx/'},
{name: 'La Coste, TX', url: '/la-coste-tx/'},
{name: 'La Feria, TX', url: '/la-feria-tx/'},
{name: 'La Grange, TX', url: '/la-grange-tx/'},
{name: 'La Joya, TX', url: '/la-joya-tx/'},
{name: 'La Marque, TX', url: '/la-marque-tx/'},
{name: 'La Porte, TX', url: '/la-porte-tx/'},
{name: 'La Pryor, TX', url: '/la-pryor-tx/'},
{name: 'La Salle, TX', url: '/la-salle-tx/'},
{name: 'La Vernia, TX', url: '/la-vernia-tx/'},
{name: 'La Villa, TX', url: '/la-villa-tx/'},
{name: 'La Ward, TX', url: '/la-ward-tx/'},
{name: 'Ladonia, TX', url: '/ladonia-tx/'},
{name: 'Laguna Park, TX', url: '/laguna-park-tx/'},
{name: 'Laird Hill, TX', url: '/laird-hill-tx/'},
{name: 'Lake Creek, TX', url: '/lake-creek-tx/'},
{name: 'Lake Dallas, TX', url: '/lake-dallas-tx/'},
{name: 'Lake Jackson, TX', url: '/lake-jackson-tx/'},
{name: 'Lakehills, TX', url: '/lakehills-tx/'},
{name: 'Lakeview, TX', url: '/lakeview-tx/'},
{name: 'Lamesa, TX', url: '/lamesa-tx/'},
{name: 'Lampasas, TX', url: '/lampasas-tx/'},
{name: 'Lancaster, TX', url: '/lancaster-tx/'},
{name: 'Lane City, TX', url: '/lane-city-tx/'},
{name: 'Laneville, TX', url: '/laneville-tx/'},
{name: 'Langtry, TX', url: '/langtry-tx/'},
{name: 'Laredo, TX', url: '/laredo-tx/'},
{name: 'Larue, TX', url: '/larue-tx/'},
{name: 'Lasara, TX', url: '/lasara-tx/'},
{name: 'Latexo, TX', url: '/latexo-tx/'},
{name: 'Laughlin A F B, TX', url: '/laughlin-a-f-b-tx/'},
{name: 'Lavon, TX', url: '/lavon-tx/'},
{name: 'Lawn, TX', url: '/lawn-tx/'},
{name: 'Lazbuddie, TX', url: '/lazbuddie-tx/'},
{name: 'League City, TX', url: '/league-city-tx/'},
{name: 'Leakey, TX', url: '/leakey-tx/'},
{name: 'Leander, TX', url: '/leander-tx/'},
{name: 'Ledbetter, TX', url: '/ledbetter-tx/'},
{name: 'Leesburg, TX', url: '/leesburg-tx/'},
{name: 'Leesville, TX', url: '/leesville-tx/'},
{name: 'Lefors, TX', url: '/lefors-tx/'},
{name: 'Leggett, TX', url: '/leggett-tx/'},
{name: 'Lelia Lake, TX', url: '/lelia-lake-tx/'},
{name: 'Leming, TX', url: '/leming-tx/'},
{name: 'Lenorah, TX', url: '/lenorah-tx/'},
{name: 'Leona, TX', url: '/leona-tx/'},
{name: 'Leonard, TX', url: '/leonard-tx/'},
{name: 'Leroy, TX', url: '/leroy-tx/'},
{name: 'Levelland, TX', url: '/levelland-tx/'},
{name: 'Lewisville, TX', url: '/lewisville-tx/'},
{name: 'Lexington, TX', url: '/lexington-tx/'},
{name: 'Liberty Hill, TX', url: '/liberty-hill-tx/'},
{name: 'Liberty, TX', url: '/liberty-tx/'},
{name: 'Lillian, TX', url: '/lillian-tx/'},
{name: 'Lincoln, TX', url: '/lincoln-tx/'},
{name: 'Lindale, TX', url: '/lindale-tx/'},
{name: 'Linden, TX', url: '/linden-tx/'},
{name: 'Lindsay, TX', url: '/lindsay-tx/'},
{name: 'Lingleville, TX', url: '/lingleville-tx/'},
{name: 'Linn, TX', url: '/linn-tx/'},
{name: 'Lipan, TX', url: '/lipan-tx/'},
{name: 'Lipscomb, TX', url: '/lipscomb-tx/'},
{name: 'Lissie, TX', url: '/lissie-tx/'},
{name: 'Little Elm, TX', url: '/little-elm-tx/'},
{name: 'Little River Academy, TX', url: '/little-river-academy-tx/'},
{name: 'Littlefield, TX', url: '/littlefield-tx/'},
{name: 'Liverpool, TX', url: '/liverpool-tx/'},
{name: 'Livingston, TX', url: '/livingston-tx/'},
{name: 'Llano, TX', url: '/llano-tx/'},
{name: 'Lockhart, TX', url: '/lockhart-tx/'},
{name: 'Lockney, TX', url: '/lockney-tx/'},
{name: 'Lodi, TX', url: '/lodi-tx/'},
{name: 'Lohn, TX', url: '/lohn-tx/'},
{name: 'Lolita, TX', url: '/lolita-tx/'},
{name: 'Lometa, TX', url: '/lometa-tx/'},
{name: 'London, TX', url: '/london-tx/'},
{name: 'Lone Oak, TX', url: '/lone-oak-tx/'},
{name: 'Lone Star, TX', url: '/lone-star-tx/'},
{name: 'Long Branch, TX', url: '/long-branch-tx/'},
{name: 'Longview, TX', url: '/longview-tx/'},
{name: 'Loop, TX', url: '/loop-tx/'},
{name: 'Lopeno, TX', url: '/lopeno-tx/'},
{name: 'Loraine, TX', url: '/loraine-tx/'},
{name: 'Lorena, TX', url: '/lorena-tx/'},
{name: 'Lorenzo, TX', url: '/lorenzo-tx/'},
{name: 'Los Ebanos, TX', url: '/los-ebanos-tx/'},
{name: 'Los Fresnos, TX', url: '/los-fresnos-tx/'},
{name: 'Los Indios, TX', url: '/los-indios-tx/'},
{name: 'Lott, TX', url: '/lott-tx/'},
{name: 'Louise, TX', url: '/louise-tx/'},
{name: 'Lovelady, TX', url: '/lovelady-tx/'},
{name: 'Loving, TX', url: '/loving-tx/'},
{name: 'Lowake, TX', url: '/lowake-tx/'},
{name: 'Lozano, TX', url: '/lozano-tx/'},
{name: 'Lubbock, TX', url: '/lubbock-tx/'},
{name: 'Lueders, TX', url: '/lueders-tx/'},
{name: 'Lufkin, TX', url: '/lufkin-tx/'},
{name: 'Luling, TX', url: '/luling-tx/'},
{name: 'Lumberton, TX', url: '/lumberton-tx/'},
{name: 'Lyford, TX', url: '/lyford-tx/'},
{name: 'Lyons, TX', url: '/lyons-tx/'},
{name: 'Lytle, TX', url: '/lytle-tx/'},
{name: 'Mabank, TX', url: '/mabank-tx/'},
{name: 'Macdona, TX', url: '/macdona-tx/'},
{name: 'Madisonville, TX', url: '/madisonville-tx/'},
{name: 'Magnolia, TX', url: '/magnolia-tx/'},
{name: 'Malakoff, TX', url: '/malakoff-tx/'},
{name: 'Malone, TX', url: '/malone-tx/'},
{name: 'Manchaca, TX', url: '/manchaca-tx/'},
{name: 'Manor, TX', url: '/manor-tx/'},
{name: 'Mansfield, TX', url: '/mansfield-tx/'},
{name: 'Manvel, TX', url: '/manvel-tx/'},
{name: 'Maple, TX', url: '/maple-tx/'},
{name: 'Marathon, TX', url: '/marathon-tx/'},
{name: 'Marble Falls, TX', url: '/marble-falls-tx/'},
{name: 'Marfa, TX', url: '/marfa-tx/'},
{name: 'Marietta, TX', url: '/marietta-tx/'},
{name: 'Marion, TX', url: '/marion-tx/'},
{name: 'Markham, TX', url: '/markham-tx/'},
{name: 'Marlin, TX', url: '/marlin-tx/'},
{name: 'Marquez, TX', url: '/marquez-tx/'},
{name: 'Marshall, TX', url: '/marshall-tx/'},
{name: 'Mart, TX', url: '/mart-tx/'},
{name: 'Martindale, TX', url: '/martindale-tx/'},
{name: 'Martinsville, TX', url: '/martinsville-tx/'},
{name: 'Maryneal, TX', url: '/maryneal-tx/'},
{name: 'Mason, TX', url: '/mason-tx/'},
{name: 'Masterson, TX', url: '/masterson-tx/'},
{name: 'Matador, TX', url: '/matador-tx/'},
{name: 'Matagorda, TX', url: '/matagorda-tx/'},
{name: 'Mathis, TX', url: '/mathis-tx/'},
{name: 'Maud, TX', url: '/maud-tx/'},
{name: 'Mauriceville, TX', url: '/mauriceville-tx/'},
{name: 'Maxwell, TX', url: '/maxwell-tx/'},
{name: 'May, TX', url: '/may-tx/'},
{name: 'Maydelle, TX', url: '/maydelle-tx/'},
{name: 'Maypearl, TX', url: '/maypearl-tx/'},
{name: 'Mc Camey, TX', url: '/mc-camey-tx/'},
{name: 'Mc Caulley, TX', url: '/mc-caulley-tx/'},
{name: 'Mc Dade, TX', url: '/mc-dade-tx/'},
{name: 'Mc Gregor, TX', url: '/mc-gregor-tx/'},
{name: 'Mc Leod, TX', url: '/mc-leod-tx/'},
{name: 'Mc Neil, TX', url: '/mc-neil-tx/'},
{name: 'Mc Queeney, TX', url: '/mc-queeney-tx/'},
{name: 'Mcadoo, TX', url: '/mcadoo-tx/'},
{name: 'Mcallen, TX', url: '/mcallen-tx/'},
{name: 'Mcfaddin, TX', url: '/mcfaddin-tx/'},
{name: 'Mckinney, TX', url: '/mckinney-tx/'},
{name: 'Mclean, TX', url: '/mclean-tx/'},
{name: 'Meadow, TX', url: '/meadow-tx/'},
{name: 'Medina, TX', url: '/medina-tx/'},
{name: 'Megargel, TX', url: '/megargel-tx/'},
{name: 'Melissa, TX', url: '/melissa-tx/'},
{name: 'Melvin, TX', url: '/melvin-tx/'},
{name: 'Memphis, TX', url: '/memphis-tx/'},
{name: 'Menard, TX', url: '/menard-tx/'},
{name: 'Mentone, TX', url: '/mentone-tx/'},
{name: 'Mercedes, TX', url: '/mercedes-tx/'},
{name: 'Mereta, TX', url: '/mereta-tx/'},
{name: 'Meridian, TX', url: '/meridian-tx/'},
{name: 'Merit, TX', url: '/merit-tx/'},
{name: 'Merkel, TX', url: '/merkel-tx/'},
{name: 'Mertens, TX', url: '/mertens-tx/'},
{name: 'Mertzon, TX', url: '/mertzon-tx/'},
{name: 'Mesquite, TX', url: '/mesquite-tx/'},
{name: 'Mexia, TX', url: '/mexia-tx/'},
{name: 'Meyersville, TX', url: '/meyersville-tx/'},
{name: 'Miami, TX', url: '/miami-tx/'},
{name: 'Mico, TX', url: '/mico-tx/'},
{name: 'Midfield, TX', url: '/midfield-tx/'},
{name: 'Midkiff, TX', url: '/midkiff-tx/'},
{name: 'Midland, TX', url: '/midland-tx/'},
{name: 'Midlothian, TX', url: '/midlothian-tx/'},
{name: 'Midway, TX', url: '/midway-tx/'},
{name: 'Milam, TX', url: '/milam-tx/'},
{name: 'Milano, TX', url: '/milano-tx/'},
{name: 'Miles, TX', url: '/miles-tx/'},
{name: 'Milford, TX', url: '/milford-tx/'},
{name: 'Millersview, TX', url: '/millersview-tx/'},
{name: 'Millican, TX', url: '/millican-tx/'},
{name: 'Millsap, TX', url: '/millsap-tx/'},
{name: 'Minden, TX', url: '/minden-tx/'},
{name: 'Mineola, TX', url: '/mineola-tx/'},
{name: 'Mineral Wells, TX', url: '/mineral-wells-tx/'},
{name: 'Mineral, TX', url: '/mineral-tx/'},
{name: 'Mingus, TX', url: '/mingus-tx/'},
{name: 'Mirando City, TX', url: '/mirando-city-tx/'},
{name: 'Mission, TX', url: '/mission-tx/'},
{name: 'Missouri City, TX', url: '/missouri-city-tx/'},
{name: 'Mobeetie, TX', url: '/mobeetie-tx/'},
{name: 'Monahans, TX', url: '/monahans-tx/'},
{name: 'Mont Belvieu, TX', url: '/mont-belvieu-tx/'},
{name: 'Montague, TX', url: '/montague-tx/'},
{name: 'Montalba, TX', url: '/montalba-tx/'},
{name: 'Montgomery, TX', url: '/montgomery-tx/'},
{name: 'Moody, TX', url: '/moody-tx/'},
{name: 'Moore, TX', url: '/moore-tx/'},
{name: 'Moran, TX', url: '/moran-tx/'},
{name: 'Morgan Mill, TX', url: '/morgan-mill-tx/'},
{name: 'Morgan, TX', url: '/morgan-tx/'},
{name: 'Morse, TX', url: '/morse-tx/'},
{name: 'Morton, TX', url: '/morton-tx/'},
{name: 'Moscow, TX', url: '/moscow-tx/'},
{name: 'Moulton, TX', url: '/moulton-tx/'},
{name: 'Mound, TX', url: '/mound-tx/'},
{name: 'Mount Calm, TX', url: '/mount-calm-tx/'},
{name: 'Mount Enterprise, TX', url: '/mount-enterprise-tx/'},
{name: 'Mount Pleasant, TX', url: '/mount-pleasant-tx/'},
{name: 'Mount Vernon, TX', url: '/mount-vernon-tx/'},
{name: 'Mountain Home, TX', url: '/mountain-home-tx/'},
{name: 'Muenster, TX', url: '/muenster-tx/'},
{name: 'Muldoon, TX', url: '/muldoon-tx/'},
{name: 'Muleshoe, TX', url: '/muleshoe-tx/'},
{name: 'Mullin, TX', url: '/mullin-tx/'},
{name: 'Mumford, TX', url: '/mumford-tx/'},
{name: 'Munday, TX', url: '/munday-tx/'},
{name: 'Murchison, TX', url: '/murchison-tx/'},
{name: 'Myra, TX', url: '/myra-tx/'},
{name: 'Nacogdoches, TX', url: '/nacogdoches-tx/'},
{name: 'Nada, TX', url: '/nada-tx/'},
{name: 'Naples, TX', url: '/naples-tx/'},
{name: 'Nash, TX', url: '/nash-tx/'},
{name: 'Natalia, TX', url: '/natalia-tx/'},
{name: 'Naval Air Station Jrb, TX', url: '/naval-air-station-jrb-tx/'},
{name: 'Navasota, TX', url: '/navasota-tx/'},
{name: 'Nazareth, TX', url: '/nazareth-tx/'},
{name: 'Neches, TX', url: '/neches-tx/'},
{name: 'Nederland, TX', url: '/nederland-tx/'},
{name: 'Needville, TX', url: '/needville-tx/'},
{name: 'Nemo, TX', url: '/nemo-tx/'},
{name: 'Nevada, TX', url: '/nevada-tx/'},
{name: 'New Baden, TX', url: '/new-baden-tx/'},
{name: 'New Boston, TX', url: '/new-boston-tx/'},
{name: 'New Braunfels, TX', url: '/new-braunfels-tx/'},
{name: 'New Caney, TX', url: '/new-caney-tx/'},
{name: 'New Deal, TX', url: '/new-deal-tx/'},
{name: 'New Home, TX', url: '/new-home-tx/'},
{name: 'New London, TX', url: '/new-london-tx/'},
{name: 'New Summerfield, TX', url: '/new-summerfield-tx/'},
{name: 'New Ulm, TX', url: '/new-ulm-tx/'},
{name: 'New Waverly, TX', url: '/new-waverly-tx/'},
{name: 'Newark, TX', url: '/newark-tx/'},
{name: 'Newcastle, TX', url: '/newcastle-tx/'},
{name: 'Newton, TX', url: '/newton-tx/'},
{name: 'Nixon, TX', url: '/nixon-tx/'},
{name: 'Nocona, TX', url: '/nocona-tx/'},
{name: 'Nolan, TX', url: '/nolan-tx/'},
{name: 'Nolanville, TX', url: '/nolanville-tx/'},
{name: 'Nome, TX', url: '/nome-tx/'},
{name: 'Nordheim, TX', url: '/nordheim-tx/'},
{name: 'Normangee, TX', url: '/normangee-tx/'},
{name: 'Normanna, TX', url: '/normanna-tx/'},
{name: 'North Houston, TX', url: '/north-houston-tx/'},
{name: 'North Richland Hills, TX', url: '/north-richland-hills-tx/'},
{name: 'North Zulch, TX', url: '/north-zulch-tx/'},
{name: 'Norton, TX', url: '/norton-tx/'},
{name: 'Notrees, TX', url: '/notrees-tx/'},
{name: 'Novice, TX', url: '/novice-tx/'},
{name: 'Nursery, TX', url: '/nursery-tx/'},
{name: 'O Brien, TX', url: '/o-brien-tx/'},
{name: 'Oakhurst, TX', url: '/oakhurst-tx/'},
{name: 'Oakland, TX', url: '/oakland-tx/'},
{name: 'Oakville, TX', url: '/oakville-tx/'},
{name: 'Oakwood, TX', url: '/oakwood-tx/'},
{name: 'Odell, TX', url: '/odell-tx/'},
{name: 'Odem, TX', url: '/odem-tx/'},
{name: 'Odessa, TX', url: '/odessa-tx/'},
{name: 'Odonnell, TX', url: '/odonnell-tx/'},
{name: 'Oglesby, TX', url: '/oglesby-tx/'},
{name: 'Oilton, TX', url: '/oilton-tx/'},
{name: 'Oklaunion, TX', url: '/oklaunion-tx/'},
{name: 'Old Glory, TX', url: '/old-glory-tx/'},
{name: 'Old Ocean, TX', url: '/old-ocean-tx/'},
{name: 'Olden, TX', url: '/olden-tx/'},
{name: 'Olmito, TX', url: '/olmito-tx/'},
{name: 'Olney, TX', url: '/olney-tx/'},
{name: 'Olton, TX', url: '/olton-tx/'},
{name: 'Omaha, TX', url: '/omaha-tx/'},
{name: 'Onalaska, TX', url: '/onalaska-tx/'},
{name: 'Orange Grove, TX', url: '/orange-grove-tx/'},
{name: 'Orange, TX', url: '/orange-tx/'},
{name: 'Orangefield, TX', url: '/orangefield-tx/'},
{name: 'Orchard, TX', url: '/orchard-tx/'},
{name: 'Ore City, TX', url: '/ore-city-tx/'},
{name: 'Orla, TX', url: '/orla-tx/'},
{name: 'Ottine, TX', url: '/ottine-tx/'},
{name: 'Ovalo, TX', url: '/ovalo-tx/'},
{name: 'Overton, TX', url: '/overton-tx/'},
{name: 'Ozona, TX', url: '/ozona-tx/'},
{name: 'Paducah, TX', url: '/paducah-tx/'},
{name: 'Paige, TX', url: '/paige-tx/'},
{name: 'Paint Rock, TX', url: '/paint-rock-tx/'},
{name: 'Palacios, TX', url: '/palacios-tx/'},
{name: 'Palestine, TX', url: '/palestine-tx/'},
{name: 'Palmer, TX', url: '/palmer-tx/'},
{name: 'Palo Pinto, TX', url: '/palo-pinto-tx/'},
{name: 'Paluxy, TX', url: '/paluxy-tx/'},
{name: 'Pampa, TX', url: '/pampa-tx/'},
{name: 'Pandora, TX', url: '/pandora-tx/'},
{name: 'Panhandle, TX', url: '/panhandle-tx/'},
{name: 'Panna Maria, TX', url: '/panna-maria-tx/'},
{name: 'Panola, TX', url: '/panola-tx/'},
{name: 'Paradise, TX', url: '/paradise-tx/'},
{name: 'Paris, TX', url: '/paris-tx/'},
{name: 'Pasadena, TX', url: '/pasadena-tx/'},
{name: 'Pattison, TX', url: '/pattison-tx/'},
{name: 'Pattonville, TX', url: '/pattonville-tx/'},
{name: 'Pawnee, TX', url: '/pawnee-tx/'},
{name: 'Pearland, TX', url: '/pearland-tx/'},
{name: 'Pearsall, TX', url: '/pearsall-tx/'},
{name: 'Peaster, TX', url: '/peaster-tx/'},
{name: 'Pecan Gap, TX', url: '/pecan-gap-tx/'},
{name: 'Pecos, TX', url: '/pecos-tx/'},
{name: 'Peggy, TX', url: '/peggy-tx/'},
{name: 'Pendleton, TX', url: '/pendleton-tx/'},
{name: 'Penelope, TX', url: '/penelope-tx/'},
{name: 'Penitas, TX', url: '/penitas-tx/'},
{name: 'Pennington, TX', url: '/pennington-tx/'},
{name: 'Penwell, TX', url: '/penwell-tx/'},
{name: 'Pep, TX', url: '/pep-tx/'},
{name: 'Perrin, TX', url: '/perrin-tx/'},
{name: 'Perryton, TX', url: '/perryton-tx/'},
{name: 'Petersburg, TX', url: '/petersburg-tx/'},
{name: 'Petrolia, TX', url: '/petrolia-tx/'},
{name: 'Pettus, TX', url: '/pettus-tx/'},
{name: 'Petty, TX', url: '/petty-tx/'},
{name: 'Pflugerville, TX', url: '/pflugerville-tx/'},
{name: 'Pharr, TX', url: '/pharr-tx/'},
{name: 'Pickton, TX', url: '/pickton-tx/'},
{name: 'Pierce, TX', url: '/pierce-tx/'},
{name: 'Pilot Point, TX', url: '/pilot-point-tx/'},
{name: 'Pinehurst, TX', url: '/pinehurst-tx/'},
{name: 'Pineland, TX', url: '/pineland-tx/'},
{name: 'Pittsburg, TX', url: '/pittsburg-tx/'},
{name: 'Placedo, TX', url: '/placedo-tx/'},
{name: 'Plains, TX', url: '/plains-tx/'},
{name: 'Plainview, TX', url: '/plainview-tx/'},
{name: 'Plano, TX', url: '/plano-tx/'},
{name: 'Plantersville, TX', url: '/plantersville-tx/'},
{name: 'Pleasanton, TX', url: '/pleasanton-tx/'},
{name: 'Pledger, TX', url: '/pledger-tx/'},
{name: 'Plum, TX', url: '/plum-tx/'},
{name: 'Point Comfort, TX', url: '/point-comfort-tx/'},
{name: 'Point, TX', url: '/point-tx/'},
{name: 'Pointblank, TX', url: '/pointblank-tx/'},
{name: 'Pollok, TX', url: '/pollok-tx/'},
{name: 'Ponder, TX', url: '/ponder-tx/'},
{name: 'Pontotoc, TX', url: '/pontotoc-tx/'},
{name: 'Poolville, TX', url: '/poolville-tx/'},
{name: 'Port Aransas, TX', url: '/port-aransas-tx/'},
{name: 'Port Arthur, TX', url: '/port-arthur-tx/'},
{name: 'Port Bolivar, TX', url: '/port-bolivar-tx/'},
{name: 'Port Isabel, TX', url: '/port-isabel-tx/'},
{name: 'Port Lavaca, TX', url: '/port-lavaca-tx/'},
{name: 'Port Mansfield, TX', url: '/port-mansfield-tx/'},
{name: 'Port Neches, TX', url: '/port-neches-tx/'},
{name: 'Port O Connor, TX', url: '/port-o-connor-tx/'},
{name: 'Porter, TX', url: '/porter-tx/'},
{name: 'Portland, TX', url: '/portland-tx/'},
{name: 'Post, TX', url: '/post-tx/'},
{name: 'Poteet, TX', url: '/poteet-tx/'},
{name: 'Poth, TX', url: '/poth-tx/'},
{name: 'Pottsboro, TX', url: '/pottsboro-tx/'},
{name: 'Pottsville, TX', url: '/pottsville-tx/'},
{name: 'Powderly, TX', url: '/powderly-tx/'},
{name: 'Powell, TX', url: '/powell-tx/'},
{name: 'Poynor, TX', url: '/poynor-tx/'},
{name: 'Prairie Hill, TX', url: '/prairie-hill-tx/'},
{name: 'Prairie Lea, TX', url: '/prairie-lea-tx/'},
{name: 'Prairie View, TX', url: '/prairie-view-tx/'},
{name: 'Premont, TX', url: '/premont-tx/'},
{name: 'Presidio, TX', url: '/presidio-tx/'},
{name: 'Price, TX', url: '/price-tx/'},
{name: 'Priddy, TX', url: '/priddy-tx/'},
{name: 'Princeton, TX', url: '/princeton-tx/'},
{name: 'Proctor, TX', url: '/proctor-tx/'},
{name: 'Progreso, TX', url: '/progreso-tx/'},
{name: 'Prosper, TX', url: '/prosper-tx/'},
{name: 'Purdon, TX', url: '/purdon-tx/'},
{name: 'Purmela, TX', url: '/purmela-tx/'},
{name: 'Putnam, TX', url: '/putnam-tx/'},
{name: 'Pyote, TX', url: '/pyote-tx/'},
{name: 'Quail, TX', url: '/quail-tx/'},
{name: 'Quanah, TX', url: '/quanah-tx/'},
{name: 'Queen City, TX', url: '/queen-city-tx/'},
{name: 'Quemado, TX', url: '/quemado-tx/'},
{name: 'Quinlan, TX', url: '/quinlan-tx/'},
{name: 'Quitaque, TX', url: '/quitaque-tx/'},
{name: 'Quitman, TX', url: '/quitman-tx/'},
{name: 'Rainbow, TX', url: '/rainbow-tx/'},
{name: 'Ralls, TX', url: '/ralls-tx/'},
{name: 'Randolph, TX', url: '/randolph-tx/'},
{name: 'Ranger, TX', url: '/ranger-tx/'},
{name: 'Rankin, TX', url: '/rankin-tx/'},
{name: 'Ransom Canyon, TX', url: '/ransom-canyon-tx/'},
{name: 'Ratcliff, TX', url: '/ratcliff-tx/'},
{name: 'Ravenna, TX', url: '/ravenna-tx/'},
{name: 'Raymondville, TX', url: '/raymondville-tx/'},
{name: 'Raywood, TX', url: '/raywood-tx/'},
{name: 'Reagan, TX', url: '/reagan-tx/'},
{name: 'Realitos, TX', url: '/realitos-tx/'},
{name: 'Red Oak, TX', url: '/red-oak-tx/'},
{name: 'Red Rock, TX', url: '/red-rock-tx/'},
{name: 'Redford, TX', url: '/redford-tx/'},
{name: 'Redwater, TX', url: '/redwater-tx/'},
{name: 'Refugio, TX', url: '/refugio-tx/'},
{name: 'Reklaw, TX', url: '/reklaw-tx/'},
{name: 'Rhome, TX', url: '/rhome-tx/'},
{name: 'Rice, TX', url: '/rice-tx/'},
{name: 'Richards, TX', url: '/richards-tx/'},
{name: 'Richardson, TX', url: '/richardson-tx/'},
{name: 'Richland Springs, TX', url: '/richland-springs-tx/'},
{name: 'Richland, TX', url: '/richland-tx/'},
{name: 'Richmond, TX', url: '/richmond-tx/'},
{name: 'Riesel, TX', url: '/riesel-tx/'},
{name: 'Ringgold, TX', url: '/ringgold-tx/'},
{name: 'Rio Frio, TX', url: '/rio-frio-tx/'},
{name: 'Rio Grande City, TX', url: '/rio-grande-city-tx/'},
{name: 'Rio Hondo, TX', url: '/rio-hondo-tx/'},
{name: 'Rio Medina, TX', url: '/rio-medina-tx/'},
{name: 'Rio Vista, TX', url: '/rio-vista-tx/'},
{name: 'Rising Star, TX', url: '/rising-star-tx/'},
{name: 'Riverside, TX', url: '/riverside-tx/'},
{name: 'Riviera, TX', url: '/riviera-tx/'},
{name: 'Roanoke, TX', url: '/roanoke-tx/'},
{name: 'Roans Prairie, TX', url: '/roans-prairie-tx/'},
{name: 'Roaring Springs, TX', url: '/roaring-springs-tx/'},
{name: 'Robert Lee, TX', url: '/robert-lee-tx/'},
{name: 'Robstown, TX', url: '/robstown-tx/'},
{name: 'Roby, TX', url: '/roby-tx/'},
{name: 'Rochelle, TX', url: '/rochelle-tx/'},
{name: 'Rochester, TX', url: '/rochester-tx/'},
{name: 'Rock Island, TX', url: '/rock-island-tx/'},
{name: 'Rockdale, TX', url: '/rockdale-tx/'},
{name: 'Rockport, TX', url: '/rockport-tx/'},
{name: 'Rocksprings, TX', url: '/rocksprings-tx/'},
{name: 'Rockwall, TX', url: '/rockwall-tx/'},
{name: 'Rockwood, TX', url: '/rockwood-tx/'},
{name: 'Rogers, TX', url: '/rogers-tx/'},
{name: 'Roma, TX', url: '/roma-tx/'},
{name: 'Romayor, TX', url: '/romayor-tx/'},
{name: 'Roosevelt, TX', url: '/roosevelt-tx/'},
{name: 'Ropesville, TX', url: '/ropesville-tx/'},
{name: 'Rosanky, TX', url: '/rosanky-tx/'},
{name: 'Roscoe, TX', url: '/roscoe-tx/'},
{name: 'Rosebud, TX', url: '/rosebud-tx/'},
{name: 'Rosenberg, TX', url: '/rosenberg-tx/'},
{name: 'Rosharon, TX', url: '/rosharon-tx/'},
{name: 'Ross, TX', url: '/ross-tx/'},
{name: 'Rosser, TX', url: '/rosser-tx/'},
{name: 'Rosston, TX', url: '/rosston-tx/'},
{name: 'Rotan, TX', url: '/rotan-tx/'},
{name: 'Round Mountain, TX', url: '/round-mountain-tx/'},
{name: 'Round Rock, TX', url: '/round-rock-tx/'},
{name: 'Round Top, TX', url: '/round-top-tx/'},
{name: 'Rowena, TX', url: '/rowena-tx/'},
{name: 'Rowlett, TX', url: '/rowlett-tx/'},
{name: 'Roxton, TX', url: '/roxton-tx/'},
{name: 'Royse City, TX', url: '/royse-city-tx/'},
{name: 'Rule, TX', url: '/rule-tx/'},
{name: 'Runge, TX', url: '/runge-tx/'},
{name: 'Rusk, TX', url: '/rusk-tx/'},
{name: 'Rye, TX', url: '/rye-tx/'},
{name: 'Sabinal, TX', url: '/sabinal-tx/'},
{name: 'Sabine Pass, TX', url: '/sabine-pass-tx/'},
{name: 'Sachse, TX', url: '/sachse-tx/'},
{name: 'Sacul, TX', url: '/sacul-tx/'},
{name: 'Sadler, TX', url: '/sadler-tx/'},
{name: 'Saint Hedwig, TX', url: '/saint-hedwig-tx/'},
{name: 'Saint Jo, TX', url: '/saint-jo-tx/'},
{name: 'Salado, TX', url: '/salado-tx/'},
{name: 'Salineno, TX', url: '/salineno-tx/'},
{name: 'Salt Flat, TX', url: '/salt-flat-tx/'},
{name: 'Saltillo, TX', url: '/saltillo-tx/'},
{name: 'Sam Norwood, TX', url: '/sam-norwood-tx/'},
{name: 'San Angelo, TX', url: '/san-angelo-tx/'},
{name: 'San Antonio, TX', url: '/san-antonio-tx/'},
{name: 'San Augustine, TX', url: '/san-augustine-tx/'},
{name: 'San Benito, TX', url: '/san-benito-tx/'},
{name: 'San Diego, TX', url: '/san-diego-tx/'},
{name: 'San Elizario, TX', url: '/san-elizario-tx/'},
{name: 'San Felipe, TX', url: '/san-felipe-tx/'},
{name: 'San Isidro, TX', url: '/san-isidro-tx/'},
{name: 'San Juan, TX', url: '/san-juan-tx/'},
{name: 'San Marcos, TX', url: '/san-marcos-tx/'},
{name: 'San Perlita, TX', url: '/san-perlita-tx/'},
{name: 'San Saba, TX', url: '/san-saba-tx/'},
{name: 'San Ygnacio, TX', url: '/san-ygnacio-tx/'},
{name: 'Sanderson, TX', url: '/sanderson-tx/'},
{name: 'Sandia, TX', url: '/sandia-tx/'},
{name: 'Sanford, TX', url: '/sanford-tx/'},
{name: 'Sanger, TX', url: '/sanger-tx/'},
{name: 'Santa Anna, TX', url: '/santa-anna-tx/'},
{name: 'Santa Elena, TX', url: '/santa-elena-tx/'},
{name: 'Santa Fe, TX', url: '/santa-fe-tx/'},
{name: 'Santa Maria, TX', url: '/santa-maria-tx/'},
{name: 'Santa Rosa, TX', url: '/santa-rosa-tx/'},
{name: 'Santo, TX', url: '/santo-tx/'},
{name: 'Saragosa, TX', url: '/saragosa-tx/'},
{name: 'Saratoga, TX', url: '/saratoga-tx/'},
{name: 'Sarita, TX', url: '/sarita-tx/'},
{name: 'Satin, TX', url: '/satin-tx/'},
{name: 'Savoy, TX', url: '/savoy-tx/'},
{name: 'Schertz, TX', url: '/schertz-tx/'},
{name: 'Schulenburg, TX', url: '/schulenburg-tx/'},
{name: 'Schwertner, TX', url: '/schwertner-tx/'},
{name: 'Scotland, TX', url: '/scotland-tx/'},
{name: 'Scottsville, TX', url: '/scottsville-tx/'},
{name: 'Scroggins, TX', url: '/scroggins-tx/'},
{name: 'Scurry, TX', url: '/scurry-tx/'},
{name: 'Seabrook, TX', url: '/seabrook-tx/'},
{name: 'Seadrift, TX', url: '/seadrift-tx/'},
{name: 'Seagoville, TX', url: '/seagoville-tx/'},
{name: 'Seagraves, TX', url: '/seagraves-tx/'},
{name: 'Sealy, TX', url: '/sealy-tx/'},
{name: 'Sebastian, TX', url: '/sebastian-tx/'},
{name: 'Seguin, TX', url: '/seguin-tx/'},
{name: 'Selman City, TX', url: '/selman-city-tx/'},
{name: 'Seminole, TX', url: '/seminole-tx/'},
{name: 'Seymour, TX', url: '/seymour-tx/'},
{name: 'Shallowater, TX', url: '/shallowater-tx/'},
{name: 'Shamrock, TX', url: '/shamrock-tx/'},
{name: 'Sheffield, TX', url: '/sheffield-tx/'},
{name: 'Shelbyville, TX', url: '/shelbyville-tx/'},
{name: 'Shepherd, TX', url: '/shepherd-tx/'},
{name: 'Sheppard Afb, TX', url: '/sheppard-afb-tx/'},
{name: 'Sheridan, TX', url: '/sheridan-tx/'},
{name: 'Sherman, TX', url: '/sherman-tx/'},
{name: 'Shiner, TX', url: '/shiner-tx/'},
{name: 'Shiro, TX', url: '/shiro-tx/'},
{name: 'Sidney, TX', url: '/sidney-tx/'},
{name: 'Sierra Blanca, TX', url: '/sierra-blanca-tx/'},
{name: 'Silsbee, TX', url: '/silsbee-tx/'},
{name: 'Silver, TX', url: '/silver-tx/'},
{name: 'Silverton, TX', url: '/silverton-tx/'},
{name: 'Simms, TX', url: '/simms-tx/'},
{name: 'Simonton, TX', url: '/simonton-tx/'},
{name: 'Sinton, TX', url: '/sinton-tx/'},
{name: 'Skellytown, TX', url: '/skellytown-tx/'},
{name: 'Skidmore, TX', url: '/skidmore-tx/'},
{name: 'Slaton, TX', url: '/slaton-tx/'},
{name: 'Slidell, TX', url: '/slidell-tx/'},
{name: 'Smiley, TX', url: '/smiley-tx/'},
{name: 'Smithville, TX', url: '/smithville-tx/'},
{name: 'Smyer, TX', url: '/smyer-tx/'},
{name: 'Snook, TX', url: '/snook-tx/'},
{name: 'Snyder, TX', url: '/snyder-tx/'},
{name: 'Somerset, TX', url: '/somerset-tx/'},
{name: 'Somerville, TX', url: '/somerville-tx/'},
{name: 'Sonora, TX', url: '/sonora-tx/'},
{name: 'Sour Lake, TX', url: '/sour-lake-tx/'},
{name: 'South Bend, TX', url: '/south-bend-tx/'},
{name: 'South Houston, TX', url: '/south-houston-tx/'},
{name: 'South Padre Island, TX', url: '/south-padre-island-tx/'},
{name: 'South Plains, TX', url: '/south-plains-tx/'},
{name: 'Southlake, TX', url: '/southlake-tx/'},
{name: 'Southmayd, TX', url: '/southmayd-tx/'},
{name: 'Spade, TX', url: '/spade-tx/'},
{name: 'Spearman, TX', url: '/spearman-tx/'},
{name: 'Spicewood, TX', url: '/spicewood-tx/'},
{name: 'Splendora, TX', url: '/splendora-tx/'},
{name: 'Spring Branch, TX', url: '/spring-branch-tx/'},
{name: 'Spring, TX', url: '/spring-tx/'},
{name: 'Springlake, TX', url: '/springlake-tx/'},
{name: 'Springtown, TX', url: '/springtown-tx/'},
{name: 'Spur, TX', url: '/spur-tx/'},
{name: 'Spurger, TX', url: '/spurger-tx/'},
{name: 'Stafford, TX', url: '/stafford-tx/'},
{name: 'Stamford, TX', url: '/stamford-tx/'},
{name: 'Stanton, TX', url: '/stanton-tx/'},
{name: 'Staples, TX', url: '/staples-tx/'},
{name: 'Star, TX', url: '/star-tx/'},
{name: 'Stephenville, TX', url: '/stephenville-tx/'},
{name: 'Sterling City, TX', url: '/sterling-city-tx/'},
{name: 'Stinnett, TX', url: '/stinnett-tx/'},
{name: 'Stockdale, TX', url: '/stockdale-tx/'},
{name: 'Stonewall, TX', url: '/stonewall-tx/'},
{name: 'Stowell, TX', url: '/stowell-tx/'},
{name: 'Stratford, TX', url: '/stratford-tx/'},
{name: 'Strawn, TX', url: '/strawn-tx/'},
{name: 'Streetman, TX', url: '/streetman-tx/'},
{name: 'Sublime, TX', url: '/sublime-tx/'},
{name: 'Sudan, TX', url: '/sudan-tx/'},
{name: 'Sugar Land, TX', url: '/sugar-land-tx/'},
{name: 'Sullivan City, TX', url: '/sullivan-city-tx/'},
{name: 'Sulphur Bluff, TX', url: '/sulphur-bluff-tx/'},
{name: 'Sulphur Springs, TX', url: '/sulphur-springs-tx/'},
{name: 'Summerfield, TX', url: '/summerfield-tx/'},
{name: 'Sumner, TX', url: '/sumner-tx/'},
{name: 'Sundown, TX', url: '/sundown-tx/'},
{name: 'Sunnyvale, TX', url: '/sunnyvale-tx/'},
{name: 'Sunray, TX', url: '/sunray-tx/'},
{name: 'Sunset, TX', url: '/sunset-tx/'},
{name: 'Sutherland Springs, TX', url: '/sutherland-springs-tx/'},
{name: 'Sweeny, TX', url: '/sweeny-tx/'},
{name: 'Sweet Home, TX', url: '/sweet-home-tx/'},
{name: 'Sweetwater, TX', url: '/sweetwater-tx/'},
{name: 'Sylvester, TX', url: '/sylvester-tx/'},
{name: 'Taft, TX', url: '/taft-tx/'},
{name: 'Tahoka, TX', url: '/tahoka-tx/'},
{name: 'Talco, TX', url: '/talco-tx/'},
{name: 'Talpa, TX', url: '/talpa-tx/'},
{name: 'Tarpley, TX', url: '/tarpley-tx/'},
{name: 'Tarzan, TX', url: '/tarzan-tx/'},
{name: 'Tatum, TX', url: '/tatum-tx/'},
{name: 'Taylor, TX', url: '/taylor-tx/'},
{name: 'Teague, TX', url: '/teague-tx/'},
{name: 'Tehuacana, TX', url: '/tehuacana-tx/'},
{name: 'Telegraph, TX', url: '/telegraph-tx/'},
{name: 'Telephone, TX', url: '/telephone-tx/'},
{name: 'Telferner, TX', url: '/telferner-tx/'},
{name: 'Tell, TX', url: '/tell-tx/'},
{name: 'Temple, TX', url: '/temple-tx/'},
{name: 'Tenaha, TX', url: '/tenaha-tx/'},
{name: 'Tennessee Colony, TX', url: '/tennessee-colony-tx/'},
{name: 'Tennyson, TX', url: '/tennyson-tx/'},
{name: 'Terlingua, TX', url: '/terlingua-tx/'},
{name: 'Terrell, TX', url: '/terrell-tx/'},
{name: 'Texarkana, TX', url: '/texarkana-tx/'},
{name: 'Texas City, TX', url: '/texas-city-tx/'},
{name: 'Texline, TX', url: '/texline-tx/'},
{name: 'The Colony, TX', url: '/the-colony-tx/'},
{name: 'Thicket, TX', url: '/thicket-tx/'},
{name: 'Thomaston, TX', url: '/thomaston-tx/'},
{name: 'Thompsons, TX', url: '/thompsons-tx/'},
{name: 'Thorndale, TX', url: '/thorndale-tx/'},
{name: 'Thornton, TX', url: '/thornton-tx/'},
{name: 'Thrall, TX', url: '/thrall-tx/'},
{name: 'Three Rivers, TX', url: '/three-rivers-tx/'},
{name: 'Throckmorton, TX', url: '/throckmorton-tx/'},
{name: 'Tilden, TX', url: '/tilden-tx/'},
{name: 'Timpson, TX', url: '/timpson-tx/'},
{name: 'Tioga, TX', url: '/tioga-tx/'},
{name: 'Tivoli, TX', url: '/tivoli-tx/'},
{name: 'Tokio, TX', url: '/tokio-tx/'},
{name: 'Tolar, TX', url: '/tolar-tx/'},
{name: 'Tom Bean, TX', url: '/tom-bean-tx/'},
{name: 'Tomball, TX', url: '/tomball-tx/'},
{name: 'Tornillo, TX', url: '/tornillo-tx/'},
{name: 'Tow, TX', url: '/tow-tx/'},
{name: 'Toyah, TX', url: '/toyah-tx/'},
{name: 'Toyahvale, TX', url: '/toyahvale-tx/'},
{name: 'Trent, TX', url: '/trent-tx/'},
{name: 'Trenton, TX', url: '/trenton-tx/'},
{name: 'Trinidad, TX', url: '/trinidad-tx/'},
{name: 'Trinity, TX', url: '/trinity-tx/'},
{name: 'Troup, TX', url: '/troup-tx/'},
{name: 'Troy, TX', url: '/troy-tx/'},
{name: 'Tuleta, TX', url: '/tuleta-tx/'},
{name: 'Tulia, TX', url: '/tulia-tx/'},
{name: 'Turkey, TX', url: '/turkey-tx/'},
{name: 'Tuscola, TX', url: '/tuscola-tx/'},
{name: 'Tye, TX', url: '/tye-tx/'},
{name: 'Tyler, TX', url: '/tyler-tx/'},
{name: 'Tynan, TX', url: '/tynan-tx/'},
{name: 'Umbarger, TX', url: '/umbarger-tx/'},
{name: 'Universal City, TX', url: '/universal-city-tx/'},
{name: 'Utopia, TX', url: '/utopia-tx/'},
{name: 'Uvalde, TX', url: '/uvalde-tx/'},
{name: 'Valentine, TX', url: '/valentine-tx/'},
{name: 'Valera, TX', url: '/valera-tx/'},
{name: 'Valley Mills, TX', url: '/valley-mills-tx/'},
{name: 'Valley Spring, TX', url: '/valley-spring-tx/'},
{name: 'Valley View, TX', url: '/valley-view-tx/'},
{name: 'Van Alstyne, TX', url: '/van-alstyne-tx/'},
{name: 'Van Horn, TX', url: '/van-horn-tx/'},
{name: 'Van Vleck, TX', url: '/van-vleck-tx/'},
{name: 'Van, TX', url: '/van-tx/'},
{name: 'Vancourt, TX', url: '/vancourt-tx/'},
{name: 'Vanderbilt, TX', url: '/vanderbilt-tx/'},
{name: 'Vanderpool, TX', url: '/vanderpool-tx/'},
{name: 'Vega, TX', url: '/vega-tx/'},
{name: 'Venus, TX', url: '/venus-tx/'},
{name: 'Veribest, TX', url: '/veribest-tx/'},
{name: 'Vernon, TX', url: '/vernon-tx/'},
{name: 'Victoria, TX', url: '/victoria-tx/'},
{name: 'Vidor, TX', url: '/vidor-tx/'},
{name: 'Village Mills, TX', url: '/village-mills-tx/'},
{name: 'Voca, TX', url: '/voca-tx/'},
{name: 'Von Ormy, TX', url: '/von-ormy-tx/'},
{name: 'Voss, TX', url: '/voss-tx/'},
{name: 'Votaw, TX', url: '/votaw-tx/'},
{name: 'Waco, TX', url: '/waco-tx/'},
{name: 'Wadsworth, TX', url: '/wadsworth-tx/'},
{name: 'Waelder, TX', url: '/waelder-tx/'},
{name: 'Waka, TX', url: '/waka-tx/'},
{name: 'Walburg, TX', url: '/walburg-tx/'},
{name: 'Wall, TX', url: '/wall-tx/'},
{name: 'Waller, TX', url: '/waller-tx/'},
{name: 'Wallis, TX', url: '/wallis-tx/'},
{name: 'Wallisville, TX', url: '/wallisville-tx/'},
{name: 'Walnut Springs, TX', url: '/walnut-springs-tx/'},
{name: 'Warda, TX', url: '/warda-tx/'},
{name: 'Waring, TX', url: '/waring-tx/'},
{name: 'Warren, TX', url: '/warren-tx/'},
{name: 'Warrenton, TX', url: '/warrenton-tx/'},
{name: 'Washington, TX', url: '/washington-tx/'},
{name: 'Waskom, TX', url: '/waskom-tx/'},
{name: 'Water Valley, TX', url: '/water-valley-tx/'},
{name: 'Waxahachie, TX', url: '/waxahachie-tx/'},
{name: 'Wayside, TX', url: '/wayside-tx/'},
{name: 'Weatherford, TX', url: '/weatherford-tx/'},
{name: 'Webster, TX', url: '/webster-tx/'},
{name: 'Weesatche, TX', url: '/weesatche-tx/'},
{name: 'Weimar, TX', url: '/weimar-tx/'},
{name: 'Weinert, TX', url: '/weinert-tx/'},
{name: 'Weir, TX', url: '/weir-tx/'},
{name: 'Welch, TX', url: '/welch-tx/'},
{name: 'Wellborn, TX', url: '/wellborn-tx/'},
{name: 'Wellington, TX', url: '/wellington-tx/'},
{name: 'Wellman, TX', url: '/wellman-tx/'},
{name: 'Wells, TX', url: '/wells-tx/'},
{name: 'Weslaco, TX', url: '/weslaco-tx/'},
{name: 'West Columbia, TX', url: '/west-columbia-tx/'},
{name: 'West Point, TX', url: '/west-point-tx/'},
{name: 'West, TX', url: '/west-tx/'},
{name: 'Westbrook, TX', url: '/westbrook-tx/'},
{name: 'Westhoff, TX', url: '/westhoff-tx/'},
{name: 'Westminster, TX', url: '/westminster-tx/'},
{name: 'Weston, TX', url: '/weston-tx/'},
{name: 'Wharton, TX', url: '/wharton-tx/'},
{name: 'Wheeler, TX', url: '/wheeler-tx/'},
{name: 'Wheelock, TX', url: '/wheelock-tx/'},
{name: 'White Deer, TX', url: '/white-deer-tx/'},
{name: 'White Oak, TX', url: '/white-oak-tx/'},
{name: 'Whiteface, TX', url: '/whiteface-tx/'},
{name: 'Whitehouse, TX', url: '/whitehouse-tx/'},
{name: 'Whitesboro, TX', url: '/whitesboro-tx/'},
{name: 'Whitewright, TX', url: '/whitewright-tx/'},
{name: 'Whitharral, TX', url: '/whitharral-tx/'},
{name: 'Whitney, TX', url: '/whitney-tx/'},
{name: 'Whitsett, TX', url: '/whitsett-tx/'},
{name: 'Whitt, TX', url: '/whitt-tx/'},
{name: 'Wichita Falls, TX', url: '/wichita-falls-tx/'},
{name: 'Wickett, TX', url: '/wickett-tx/'},
{name: 'Wiergate, TX', url: '/wiergate-tx/'},
{name: 'Wildorado, TX', url: '/wildorado-tx/'},
{name: 'Willis, TX', url: '/willis-tx/'},
{name: 'Willow City, TX', url: '/willow-city-tx/'},
{name: 'Wills Point, TX', url: '/wills-point-tx/'},
{name: 'Wilmer, TX', url: '/wilmer-tx/'},
{name: 'Wilson, TX', url: '/wilson-tx/'},
{name: 'Wimberley, TX', url: '/wimberley-tx/'},
{name: 'Windom, TX', url: '/windom-tx/'},
{name: 'Windthorst, TX', url: '/windthorst-tx/'},
{name: 'Winfield, TX', url: '/winfield-tx/'},
{name: 'Wingate, TX', url: '/wingate-tx/'},
{name: 'Wink, TX', url: '/wink-tx/'},
{name: 'Winnie, TX', url: '/winnie-tx/'},
{name: 'Winnsboro, TX', url: '/winnsboro-tx/'},
{name: 'Winona, TX', url: '/winona-tx/'},
{name: 'Winters, TX', url: '/winters-tx/'},
{name: 'Woden, TX', url: '/woden-tx/'},
{name: 'Wolfe City, TX', url: '/wolfe-city-tx/'},
{name: 'Wolfforth, TX', url: '/wolfforth-tx/'},
{name: 'Woodlake, TX', url: '/woodlake-tx/'},
{name: 'Woodlawn, TX', url: '/woodlawn-tx/'},
{name: 'Woodsboro, TX', url: '/woodsboro-tx/'},
{name: 'Woodson, TX', url: '/woodson-tx/'},
{name: 'Woodville, TX', url: '/woodville-tx/'},
{name: 'Woodway, TX', url: '/woodway-tx/'},
{name: 'Wortham, TX', url: '/wortham-tx/'},
{name: 'Wrightsboro, TX', url: '/wrightsboro-tx/'},
{name: 'Wylie, TX', url: '/wylie-tx/'},
{name: 'Yancey, TX', url: '/yancey-tx/'},
{name: 'Yantis, TX', url: '/yantis-tx/'},
{name: 'Yoakum, TX', url: '/yoakum-tx/'},
{name: 'Yorktown, TX', url: '/yorktown-tx/'},
{name: 'Zapata, TX', url: '/zapata-tx/'},
{name: 'Zavalla, TX', url: '/zavalla-tx/'},
{name: 'Zephyr, TX', url: '/zephyr-tx/'}
];

document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('heroSearchForm');
    const input = document.getElementById('heroCitySearch');
    
    const style = document.createElement('style');
    style.innerHTML = `
        .custom-scrollbar::-webkit-scrollbar { width: 6px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(242, 140, 40, 0.4); border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(242, 140, 40, 0.8); }
    `;
    document.head.appendChild(style);
    
    if (form && input) {
        const dropdown = document.createElement('ul');
        dropdown.className = 'absolute top-[110%] left-0 right-0 bg-white/95 backdrop-blur-md border border-gray-100 shadow-2xl rounded-2xl max-h-64 overflow-y-auto hidden z-50 custom-scrollbar';
        form.parentNode.appendChild(dropdown);
        
        input.addEventListener('input', (e) => {
            const term = e.target.value.toLowerCase().trim();
            dropdown.innerHTML = '';
            if(term === '') {
                dropdown.classList.add('hidden');
                return;
            }
            
            const matches = allCities.filter(c => c.name.toLowerCase().includes(term));
            if(matches.length > 0) {
                dropdown.classList.remove('hidden');
                matches.slice(0, 15).forEach(match => {
                    const li = document.createElement('li');
                    li.className = 'px-6 py-4 hover:bg-orange-50 cursor-pointer text-gray-700 font-bold transition-colors border-b border-gray-50 last:border-none flex items-center text-left';
                    li.innerHTML = `<span class="text-brand-orange mr-3 text-lg"><i class="fa-solid fa-location-dot"></i></span>${match.name}`;
                    li.addEventListener('mousedown', () => {
                        window.location.href = match.url;
                    });
                    dropdown.appendChild(li);
                });
            } else {
                dropdown.classList.remove('hidden');
                dropdown.innerHTML = '<li class="px-6 py-4 text-gray-500 italic bg-gray-50/50 rounded-2xl text-left">No cities found matching that name.</li>';
            }
        });
        
        input.addEventListener('blur', () => {
            setTimeout(() => dropdown.classList.add('hidden'), 200);
        });
        
        form.addEventListener('submit', (e) => {
            e.preventDefault();
            const term = input.value.trim().toLowerCase();
            const match = allCities.find(c => c.name.toLowerCase().includes(term));
            if(match) {
                window.location.href = match.url;
            } else {
                let slug = term.replace(/,?\s*tx$/, '');
                slug = slug.replace(/[^a-z0-9\s]/g, '').trim().replace(/\s+/g, '-');
                if (slug) {
                    window.location.href = `/${slug}-tx/`;
                }
            }
        });
    }
});
